<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/ja/modules.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Japanese translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Jan Theofel (ETES), http://www.etes.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['summarizeFeeds']['0'] = "フィードの集約";
$GLOBALS['TL_LANG']['MOD']['summarizeFeeds']['1'] = "複数のニュースアーカイブやカレンダーを1つのRSSやAtomのフィードに集約します。";
 
?>
