<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/ja/tl_layout.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Japanese translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Jan Theofel (ETES), http://www.etes.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['summarizeFeeds']['0'] = "集約したフィード";
$GLOBALS['TL_LANG']['tl_layout']['summarizeFeeds']['1'] = "ページレイアウトに追加したい、集約したフィードを選択してください。";
 
?>
