<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/ja/tl_summarizeFeeds.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Japanese translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Jan Theofel (ETES), http://www.etes.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['new']['0'] = "新しいフィード";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['new']['1'] = "新しくフィードを作成";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['show']['0'] = "詳細";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['show']['1'] = "ID %sのフィードの詳細を標示";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['edit']['0'] = "フィードを変更";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['edit']['1'] = "ID %sのフィードを変更";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['copy']['0'] = "フィードを複製";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['copy']['1'] = "ID %sのフィードを複製";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['delete']['0'] = "フィードを削除";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['delete']['1'] = "ID %sのフィードを削除";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_legend'] = "ソース";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title_legend'] = "題名と説明";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['settings_legend'] = "設定";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource']['0'] = "ソース";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource']['1'] = "フィードを作成するソースを選択してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['newsArchives']['0'] = "ニュースアーカイブ";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['newsArchives']['1'] = "フィードを生成するニュースアーカイブを選択してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['calendar']['0'] = "カレンダー";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['calendar']['1'] = "フィードを生成するカレンダーを選択してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title']['0'] = "題名";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title']['1'] = "重複しない題名を指定してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['alias']['0'] = "エイリアス";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['alias']['1'] = "重複しないファイル名(拡張子を含めずに)入力します。XMLフィードのファイルは、インストールしたTYPOlightのルートディレクトリに、<em>name.xml</em>といった名前で自動的に生成されます。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['description']['0'] = "説明";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['description']['1'] = "集約したフィードの短い説明を入力してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['source']['0'] = "出力の設定";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['source']['1'] = "出力する内容を選択します。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['letters']['0'] = "省略した記事";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['letters']['1'] = "記事を省略した文字数を入力してください。0にすると記事の全体を使用します。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['maxItems']['0'] = "項目の最大数";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['maxItems']['1'] = "フィードの項目の数を制限できます。0にするとすべて出力します。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['language']['0'] = "言語";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['language']['1'] = "フィードのISO-639の標準による言語(例: <em>ja</em>や<em>ja_jp</em>)を入力してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['format']['0'] = "書式";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['format']['1'] = "書式を選択してください。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['feedBase']['0'] = "基準のURL";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['feedBase']['1'] = "プロトコルを含めた基準のURLを入力してください。(例: <em>http://</em>)。";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_values']['news'] = "ニュースアーカイブ";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_values']['calendar'] = "カレンダー";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['teaser'] = "ティーザー";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['text'] = "アーティクル";
 
?>
