<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/it/modules.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Italian translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Torben Stoffer (Torben) 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['summarizeFeeds']['0'] = "Summarize feeds";
$GLOBALS['TL_LANG']['MOD']['summarizeFeeds']['1'] = "Permette di creare un unico flusso RSS o Atom feed utilizzando diversi archivi news oppure calendario eventi.";
 
?>
