<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/it/tl_layout.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Italian translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Torben Stoffer (Torben) 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_layout']['summarizeFeeds']['0'] = "Summarized feeds";
$GLOBALS['TL_LANG']['tl_layout']['summarizeFeeds']['1'] = "Selezionare il Summarized feeds che si vuole aggiungere al layout";
 
?>
