<?php
/**
 * TL_ROOT/system/modules/summarizeFeeds/languages/it/tl_summarizeFeeds.php 
 * 
 * Contao extension: summarizeFeeds 1.4.5 stable 
 * Italian translation file 
 * 
 * Copyright : Torben Stoffer 2009 
 * License   : LGPL 
 * Author    : Torben Stoffer (Torben) 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['new']['0'] = "Nuovo feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['new']['1'] = "Crea un nuovo feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['show']['0'] = "Dettagli";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['show']['1'] = "Mostra dettagli del feed con ID %s";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['edit']['0'] = "Modifica feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['edit']['1'] = "Modifica archivio feed ID %s";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['copy']['0'] = "Copia feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['copy']['1'] = "Copia archivio feed ID %s";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['delete']['0'] = "Elimina feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['delete']['1'] = "Elimina feed con ID %s";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_legend'] = "Sorgente";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title_legend'] = "Titolo e descrizione";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['settings_legend'] = "Impostazioni";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource']['0'] = "Sorgente";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource']['1'] = "Selezionare la sorgente dei feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['newsArchives']['0'] = "Archivio News";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['newsArchives']['1'] = "Seleziona questa opzione per utilizzare gli archivi news";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['calendar']['0'] = "Calendario/Eventi";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['calendar']['1'] = "Seleziona questa opzione per utilizzare il calendario/eventi";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['title']['1'] = "Indicare un titolo unico";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['alias']['0'] = "Alias";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['alias']['1'] = "Qui è possibile inserire un nome univoco (senza estensione). Il file di feed XML sarà generato automaticamente nella directory root del sito, ad esempio come <em> mio-feed.xml </ em>.";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['description']['1'] = "Indicare una breve descrizione per il summarized feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['source']['0'] = "Impostazioni export";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['source']['1'] = "Qui si può selezionare cosa sarà esportato.";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['letters']['0'] = "Abbreviazione articoli";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['letters']['1'] = "Indicare a quanti caratteri si vuole abbreviare l'articolo. Se si indica 0 verrà visualizzato l'intero articolo.";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['maxItems']['0'] = "Massimo numero di elementi";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['maxItems']['1'] = "Limita il numero di elementi esportati. Lasciare vuoto o inserire 0 per includere tutti gli elementi.";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['language']['0'] = "Lingua";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['language']['1'] = "Inserisci la lingua secondo il formato RFC1766 (es: <em>it</em>, <em>en</em>, <em>en-us</em>).";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['format']['0'] = "Formato feed";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['format']['1'] = "Seleziona un formato per il feed.";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['feedBase']['0'] = "URL di base";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['feedBase']['1'] = "Inserisci un URL di base con protocollo incluso. (<em>http://</em>)";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_values']['news'] = "Archivio news";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['resource_values']['calendar'] = "Calendario/eventi";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['teaser'] = "Anteprima";
$GLOBALS['TL_LANG']['tl_summarizeFeeds']['text'] = "Articoli completi";
 
?>
